-- ═══════════════════════════════════════════════════════════
--  MEAL PREP HUB · DATABASE SCHEMA
--  Reflects the live DB after all migrations have been applied.
--  To reproduce: run this file, then run each migration in order.
--  DO NOT edit this file directly — add a new migrations/NNN_*.sql instead.
-- ═══════════════════════════════════════════════════════════


-- ── PANTRY ITEMS ────────────────────────────────────────────
-- One row per ingredient. Holds both catalog data (name,
-- category, expiry) and live state (used, partial_remaining).

CREATE TABLE IF NOT EXISTS pantry_items (
  id                  TEXT PRIMARY KEY,
  name                TEXT NOT NULL,
  name_ro             TEXT,
  category            TEXT,
  subcategory         TEXT,
  quantity            TEXT,        -- kept as text: "~1kg", "1 bunch", "638" etc.
  unit                TEXT,
  purchase_date       DATE,
  expiry_date         DATE,
  perishability_level TEXT,        -- critical | high | medium | low | stable
  storage_location    TEXT,
  notes               TEXT,
  tags                TEXT[],
  -- live state (updated by the app)
  used                BOOLEAN DEFAULT FALSE,
  used_date           DATE,
  partial_remaining   INTEGER,     -- 0–100 (% left), NULL = fully available
  created_at          TIMESTAMPTZ DEFAULT NOW(),
  updated_at          TIMESTAMPTZ DEFAULT NOW()
);

-- Auto-bump updated_at on every change
CREATE OR REPLACE FUNCTION update_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER pantry_items_updated_at
  BEFORE UPDATE ON pantry_items
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();


-- ── MEAL PLANS ──────────────────────────────────────────────
-- One row per generated week. is_active = TRUE marks the
-- current week shown in the app.

CREATE TABLE IF NOT EXISTS meal_plans (
  id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  week_label   TEXT,               -- e.g. "Week of May 10–16"
  week_focus   TEXT,               -- e.g. "🥑 Avocado · Beetroot" (shown under title)
  generated_by TEXT,               -- "claude-opus-4-6"
  generated_at TIMESTAMPTZ DEFAULT NOW(),
  notes        TEXT,
  is_active    BOOLEAN DEFAULT TRUE,
  created_at   TIMESTAMPTZ DEFAULT NOW()
);


-- ── MEAL DAYS ───────────────────────────────────────────────
-- 7 rows per meal_plan (Sun → Sat).

CREATE TABLE IF NOT EXISTS meal_days (
  id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  meal_plan_id UUID NOT NULL REFERENCES meal_plans(id) ON DELETE CASCADE,
  day_label    TEXT NOT NULL,      -- "Sunday", "Monday" …
  date         TEXT NOT NULL,      -- "May 10"
  focus        TEXT,               -- "🥑 Avocado · Beetroot"
  urgent       BOOLEAN DEFAULT FALSE,
  sort_order   INTEGER NOT NULL    -- 0–6
);


-- ── MEALS ───────────────────────────────────────────────────
-- 4 rows per meal_day (breakfast, lunch, dinner, snack).

CREATE TABLE IF NOT EXISTS meals (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  meal_day_id     UUID NOT NULL REFERENCES meal_days(id) ON DELETE CASCADE,
  meal_type       TEXT NOT NULL,   -- breakfast | lunch | dinner | snack
  emoji           TEXT,
  name            TEXT NOT NULL,
  tagline         TEXT,
  kcal_csilla     INTEGER,         -- Csilla's serving
  protein_csilla  INTEGER,
  carbs_csilla    INTEGER,
  fat_csilla      INTEGER,
  tip             TEXT,
  sort_order      INTEGER NOT NULL, -- 0=breakfast … 3=snack
  cooked          BOOLEAN DEFAULT FALSE,
  cooked_date     DATE
);


-- ── MEAL PRIORITY ───────────────────────────────────────────
-- Highlighted "use these up" ingredients shown on meal cards.

CREATE TABLE IF NOT EXISTS meal_priority (
  id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  meal_id    UUID NOT NULL REFERENCES meals(id) ON DELETE CASCADE,
  label      TEXT NOT NULL,
  urgent     BOOLEAN DEFAULT FALSE,
  sort_order INTEGER DEFAULT 0
);


-- ── MEAL INGREDIENTS ────────────────────────────────────────
-- Each ingredient linked to pantry_items by ID (no fuzzy matching).
-- pantry_item_id can be NULL for staples not tracked individually.

CREATE TABLE IF NOT EXISTS meal_ingredients (
  id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  meal_id          UUID NOT NULL REFERENCES meals(id) ON DELETE CASCADE,
  pantry_item_id   TEXT REFERENCES pantry_items(id),
  name             TEXT NOT NULL,
  quantity_csilla  TEXT,           -- Csilla's serving amount (e.g. "200", "1 tbsp")
  unit             TEXT,           -- separate unit (e.g. "g", "ml")
  is_pantry_staple BOOLEAN DEFAULT FALSE,
  urgent           BOOLEAN DEFAULT FALSE,
  sort_order       INTEGER DEFAULT 0
);


-- ── MEAL STEPS ──────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS meal_steps (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  meal_id     UUID NOT NULL REFERENCES meals(id) ON DELETE CASCADE,
  step_order  INTEGER NOT NULL,
  instruction TEXT NOT NULL
);


-- ── MEAL COOK LOG ───────────────────────────────────────────
-- Stores the per-ingredient deduction snapshot taken when a meal
-- is cooked. Used to reverse the pantry changes on uncook.

CREATE TABLE IF NOT EXISTS meal_cook_log (
  meal_id    UUID PRIMARY KEY REFERENCES meals(id) ON DELETE CASCADE,
  cooked_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  deductions JSONB NOT NULL  -- [{pantry_item_id, prev_used, prev_partial, applied_pct}]
);


-- ── HOUSEHOLD MEMBERS ───────────────────────────────────────
-- Allowlist for RLS. Adding a new member = one INSERT here.

CREATE TABLE IF NOT EXISTS household_members (
  user_id  UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  name     TEXT NOT NULL,
  added_at TIMESTAMPTZ DEFAULT NOW()
);


-- ── HELPER FUNCTIONS ────────────────────────────────────────
-- See migrations/003_meal_cook_log.sql for mark_meal_cooked()
-- and unmark_meal_cooked() definitions.

CREATE OR REPLACE FUNCTION is_household_member()
RETURNS BOOLEAN LANGUAGE sql SECURITY DEFINER STABLE AS $$
  SELECT EXISTS (
    SELECT 1 FROM household_members WHERE user_id = auth.uid()
  );
$$;


-- ═══════════════════════════════════════════════════════════
--  ROW LEVEL SECURITY
--  Only household members can read or write. Unauthenticated
--  requests are blocked. Any GitHub user who signs in but is
--  not in household_members gets empty reads and 403 on writes.
-- ═══════════════════════════════════════════════════════════

ALTER TABLE pantry_items      ENABLE ROW LEVEL SECURITY;
ALTER TABLE meal_plans        ENABLE ROW LEVEL SECURITY;
ALTER TABLE meal_days         ENABLE ROW LEVEL SECURITY;
ALTER TABLE meals             ENABLE ROW LEVEL SECURITY;
ALTER TABLE meal_priority     ENABLE ROW LEVEL SECURITY;
ALTER TABLE meal_ingredients  ENABLE ROW LEVEL SECURITY;
ALTER TABLE meal_steps        ENABLE ROW LEVEL SECURITY;
ALTER TABLE meal_cook_log     ENABLE ROW LEVEL SECURITY;
ALTER TABLE household_members ENABLE ROW LEVEL SECURITY;

CREATE POLICY "household_only" ON pantry_items     FOR ALL TO authenticated USING (is_household_member()) WITH CHECK (is_household_member());
CREATE POLICY "household_only" ON meal_plans       FOR ALL TO authenticated USING (is_household_member()) WITH CHECK (is_household_member());
CREATE POLICY "household_only" ON meal_days        FOR ALL TO authenticated USING (is_household_member()) WITH CHECK (is_household_member());
CREATE POLICY "household_only" ON meals            FOR ALL TO authenticated USING (is_household_member()) WITH CHECK (is_household_member());
CREATE POLICY "household_only" ON meal_priority    FOR ALL TO authenticated USING (is_household_member()) WITH CHECK (is_household_member());
CREATE POLICY "household_only" ON meal_ingredients FOR ALL TO authenticated USING (is_household_member()) WITH CHECK (is_household_member());
CREATE POLICY "household_only" ON meal_steps       FOR ALL TO authenticated USING (is_household_member()) WITH CHECK (is_household_member());
CREATE POLICY "household_only" ON meal_cook_log    FOR ALL TO authenticated USING (is_household_member()) WITH CHECK (is_household_member());
CREATE POLICY "household_read" ON household_members FOR SELECT TO authenticated USING (auth.uid() IN (SELECT user_id FROM household_members));
